- name: Launch EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    key_name: my-keypair        # CHANGE
    instance_type: t2.micro
    image_id: ami-0f58b397bc5c1f2e8   # CHANGE (valid AMI for ap-south-1)

  tasks:
    - name: Launch EC2
      amazon.aws.ec2_instance:
        name: my-ansible-instance
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        wait: yes
        region: ap-south-1
        security_group: my-ansible-sg
      register: ec2_out

    - name: Show Public IP
      debug:
        msg: "Instance Public IP: {{ ec2_out.instances[0].public_ip_address }}"