- name: Create S3 bucket
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create bucket
      amazon.aws.s3_bucket:
        name: my-ansible-bucket-12345   # CHANGE THIS (must be unique)
        state: present
        region: ap-south-1
      register: s3_out

    - name: Show bucket ARN
      debug:
        msg: "Bucket ARN: arn:aws:s3:::my-ansible-bucket-12345"