- name: Simple AWS ec2
  hosts: localhost
  become: yes

  vars:
    region: ap-south-1
    bucket_name: my-unique-bucket-12345623456

  tasks:
    - name: Create S3 Bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ region }}"
        state: present

