- name: Simple AWS ec2
  hosts: localhost

  vars:
    region: us-east-1
    sg_name: my-sg
    vpc_id: vpc-0e91b85f039bf4c2d

  tasks:
    - name: Create Security Group
      amazon.aws.ec2_group:
        name: "{{ sg_name }}"
        description: simple sg
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            ports: [22]
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports: [80]
            cidr_ip: 0.0.0.0/0
